services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kim2002kk
      POSTGRES_DB: maqsu_training
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Kim2002kk@db:5432/maqsu_training
    volumes:
      - .:/src

volumes:
  postgres_data: